import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      "app_title": "AutoCdC",
      "tagline_start": "Transform any ",
      "tagline_end": "into a professional specification.",
      "hero_p": "Analyze landing pages, SaaS apps, or portals to generate a complete Project Specifications document in seconds using AI.",
      "input_placeholder": "https://example.com/project",
      "btn_generate": "Generate",
      "powered_by": "Powered by Llama 3.3",
      "sections_count": "15 Detailed Sections",
      "export_formats": "MD & PDF Export",
      "step_crawling": "Crawling the website...",
      "step_metadata": "Extracting metadata...",
      "step_analysis": "Analyzing features...",
      "step_generation": "Generating professional CdC...",
      "loading_time": "This usually takes about 30-45 seconds.",
      "export": "Export",
      "export_md": "Markdown (.md)",
      "export_pdf": "Adobe PDF (.pdf)",
      "editor_mode": "Editor Mode",
      "cancel": "Cancel",
      "save_changes": "Save Changes",
      "auto_generated": "Auto-generated by AutoCdC Intelligence",
      "sections_completed": "Sections Completed",
      "last_update": "Last update",
      "just_now": "Just now",
      "regeneration": "Need a different perspective? Regenerate the entire document."
    }
  },
  fr: {
    translation: {
      "app_title": "AutoCdC",
      "tagline_start": "Transformez n'importe quelle ",
      "tagline_end": "en un cahier des charges professionnel.",
      "hero_p": "Analysez des landing pages, des SaaS ou des portails pour générer un Cahier des Charges complet en quelques secondes grâce à l'IA.",
      "input_placeholder": "https://example.com/projet",
      "btn_generate": "Générer",
      "powered_by": "Propulsé par Llama 3.3",
      "sections_count": "15 Sections Détaillées",
      "export_formats": "Export MD & PDF",
      "step_crawling": "Exploration du site web...",
      "step_metadata": "Extraction des métadonnées...",
      "step_analysis": "Analyse des fonctionnalités...",
      "step_generation": "Génération du CdC professionnel...",
      "loading_time": "Cela prend généralement 30 à 45 secondes.",
      "export": "Exporter",
      "export_md": "Markdown (.md)",
      "export_pdf": "Adobe PDF (.pdf)",
      "editor_mode": "Mode Édition",
      "cancel": "Annuler",
      "save_changes": "Enregistrer",
      "auto_generated": "Généré automatiquement par l'IA AutoCdC",
      "sections_completed": "Sections Complétées",
      "last_update": "Dernière mise à jour",
      "just_now": "À l'instant",
      "regeneration": "Besoin d'une perspective différente ? Régénérez tout le document."
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'fr',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
